name: Run Python Script and Commit Output

on:
  schedule:
    # Runs daily at 00:15 UTC (adjust as needed)
    - cron: '15 0 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create dish.py from Secret
        run: echo "${{ secrets.DIA_SCRIPT }}" > dish.py

      - name: Create EPG.json from Secret
        run: echo '${{ secrets.EPG_JSON }}' > EPG.json

      - name: Run Script
        run: python dish.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *.xml || echo "No XML files found to add."
          
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update generated XML file [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
